Aptitus\Fairs\Domain\Model\Fairs\StandColor:
    type: entity
    table: stand_color
    name: StandColor
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            nullable: true
            type: string
            length: 100
        type:
            nullable: true
            type: string
            length: 10
    manyToOne:
        stand:
            targetEntity: Aptitus\Fairs\Domain\Model\Fairs\Stand
            joinColumn:
                stand_id:
                    referencedColumnName: id
                nullable: false