version: '2'

services:
    nginx:
       image: ronaldgcr/apt_fair_backend:nginx
       depends_on:
          - memcached
    memcached:
        image: memcached:alpine
    mysql:
        image: mysql:5.5
