version: '2'

services:
  nginx:
      image: ronaldgcr/apt_fair_backend:nginx
      volumes:
        - ./:/app/
        - ./logs/nginx/:/var/log/nginx/
      extra_hosts:
        - "local.services.aptitus.com:172.18.60.1"
      ports:
        - 80:80
  cli:
    extends:
      file: docker-compose.tasks.yml
      service: cli
    depends_on:
      - mysql
      - memcached
      - nginx
    command: ["/tmp/wait-for-it.sh", "mysql:3306", "--", "composer integration-test"]
  mysql:
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: mdb_apt_fairs
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER : root
    ports:
      - 3309:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode=""
  memcached:
    image: memcached:1.4-alpine
