imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ['!event', '!doctrine', '!debug', '!request']
            handler: custom
        console:
            type:  console
            handler: custom
        custom:
            type: service
            id: monolog_cloudwatch_handler