security:
    encoders:
        'Aptitus\Fairs\Domain\Model\Users\User':
            algorithm: bcrypt
            cost: 4
    providers:
        in_memory:
            memory: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~