properties:
  id: integer
  name: string
  trade_name: string
  slug: string
  image: string
  category: string
  industry: string
  document_number: string
  model: string
  stand: string
example:
  id: 1
  name: "ATENTO"
  trade_name: "TELEATENTO DEL PERU S.A.C"
  slug: "atento"
  image: ""
  category: "Empleo"
  industry: "Call Center"
  document_number: "20876778294"
  model: "Modelo 1"
  stand: "Gold"
