properties:
  message: string
  data: array
example:
  message: "Se obtuvieron las empresas correctamente."
  data: [
    {
      "id": 1,
      "name": "Atento",
      "category": "Empleo",
      "ruc": "20876778294",
      "model": "Modelo 1",
      "stand_type": "Gold"
    },
    {
      "id": 2,
      "name": "Atento",
      "category": "Empleo",
      "ruc": "20965874784",
      "model": "Modelo 2",
      "stand_type": "Gold"
    },
    {
      "id": 3,
      "name": "UPC",
      "category": "Educación",
      "ruc": "20458745896",
      "model": "Modelo 4",
      "stand_type": "Silver"
    },
    {
      "id": 4,
      "name": "Universidad del Pacífico",
      "category": "Educación",
      "ruc": "20325487459",
      "model": "Modelo 3",
      "stand_type": "Bronze"
    }
  ]
