properties:
  message: string
  data: array
example:
  message: "Se obtuvieron las ferias correctamente."
  data: [
    {
      "id": 1,
      "name": "ExpoAptitus I",
      "created_at": "01/10/2017",
      "state": "Activo",
      "total_stands": 2,
      "total_companies": 31
    },
    {
      "id": 2,
      "name": "ExpoAptitus II",
      "created_at": "15/11/2017",
      "state": "Inactivo",
      "total_stands": 10,
      "total_companies": 18
    }
  ]
