properties:
  message: string
  data: object
example:
  message: "Se obtuvo la información de la feria correctamente."
  data: {
    "id": 1,
    "name": "ExpoAptitus I",
    "slogan": "ExpoAptitus I",
    "star_date": "01/10/2017",
    "end_date": "01/10/2017",
    "image": "https://cde.feria.g3c.pe/images/fair/5e8edf5ef2bdeb1bd697ed5c4e6aff82.png?v=12rf1234"
  }