properties:
  message: string
  token: string
example:
  message: "Se inició sesión correctamente."
  token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE0OTU0NzQ3MDQsIm5iZiI6MTQ5NTQ3NDcwNCwiZXhwIjoxNDk1NTAzNTA0LCJkYXRhIjp7ImlkIjoiMTA4MTk3MSIsImVtYWlsIjoianp1bWFldGFAZWNvZGlnaXRhbC5wZSIsIm5hbWUiOiJKb3NlcGggWnVtYWV0YSIsInJvbGUiOiJhZG1pbi1tYXN0ZXIifX0.Sixitkju4L8P8ZPJqDNWRRuyREA9kIhcZrOGNByKM5o"