properties:
  message: string
  data:
    type: object
    description: |
      Data of dependences and rules by type of stand.

      Key [list] - Data of model and amphitryon.

      Key [rules] - Rules of videos, images and colors, etc.
examples:
  1_gold:
    message: "Depedencias y reglas listadas correctamente."
    data: {
      list: {
        models: [
          {
            id: 1,
            value: "Modelo 1"
          },
          {
            id: 2,
            value: "Modelo 2"
          },
          {
            id: 3,
            value: "Modelo 3"
          },
          {
            id: 4,
            value: "Modelo 4"
          },
          {
            id: 5,
            value: "Modelo 5"
          }
        ],
        amphitryons: [
          {
            id: 1,
            value: "Anfitriona 1"
          },
          {
            id: 2,
            value: "Anfitriona 2"
          },
          {
            id: 3,
            value: "Anfitriona 3"
          },
          {
            id: 4,
            value: "Anfitriona 4"
          },
          {
            id: 5,
            value: "Anfitriona 5"
          },
          {
            id: 6,
            value: "Anfitriona 6"
          },
          {
            id: 7,
            value: "Anfitriona 7"
          },
          {
            id: 8,
            value: "Anfitriona 8"
          }
        ]
      },
      rules: [
        "image_monitor": {
          "required": true
        },
        "image_totem": {
          "required": true
        },
        "image_banderole_1": {
          "required": true
        },
        "image_banderole_2": {
          "required": true
        },
        "image_top": {
          "required": true
        },
        "image_counter": {
          "required": true
        },
        "color_1": {
          "required": true
        },
        "color_2": {
          "required": true
        },
        "amphitryon": {
          "required": true
        },
        "video": {
          "required": false
        }
      ]
    }
  2_silver:
    message: "Depedencias y reglas listadas correctamente."
    data: {
      list: {
        models: [
          {
            id: 6,
            value: "Modelo 6"
          },
          {
            id: 7,
            value: "Modelo 7"
          },
          {
            id: 8,
            value: "Modelo 8"
          }
        ],
        amphitryons: [
          {
            id: 1,
            value: "Anfitriona 1"
          },
          {
            id: 2,
            value: "Anfitriona 2"
          },
          {
            id: 3,
            value: "Anfitriona 3"
          },
          {
            id: 4,
            value: "Anfitriona 4"
          },
          {
            id: 5,
            value: "Anfitriona 5"
          },
          {
            id: 6,
            value: "Anfitriona 6"
          },
          {
            id: 7,
            value: "Anfitriona 7"
          },
          {
            id: 8,
            value: "Anfitriona 8"
          }
        ]
      },
      rules: [
        "image_monitor": {
          "required": true
        },
        "image_totem": {
          "required": true
        },
        "image_poster_1": {
          "required": true
        },
        "image_top": {
          "required": true
        },
        "image_counter": {
          "required": true
        },
        "color_1": {
          "required": true
        },
        "color_2": {
          "required": true
        },
        "amphitryon": {
          "required": true
        },
        "video": {
          "required": false
        }
      ]
    }
  3_bronze:
    message: "Depedencias y reglas listadas correctamente."
    data: {
      list: {
        models: [
          {
            id: 9,
            value: "Modelo 9"
          }
        ],
        amphitryons: [
          {
            id: 1,
            value: "Anfitriona 1"
          },
          {
            id: 2,
            value: "Anfitriona 2"
          },
          {
            id: 3,
            value: "Anfitriona 3"
          },
          {
            id: 4,
            value: "Anfitriona 4"
          },
          {
            id: 5,
            value: "Anfitriona 5"
          },
          {
            id: 6,
            value: "Anfitriona 6"
          },
          {
            id: 7,
            value: "Anfitriona 7"
          },
          {
            id: 8,
            value: "Anfitriona 8"
          }
        ]
      },
      rules: [
        "image_monitor": {
          "required": true
        },
        "image_banderole_1": {
          "required": true
        },
        "image_poster_1": {
          "required": true
        },
        "image_top": {
          "required": true
        },
        "image_counter": {
          "required": true
        },
        "color_1": {
          "required": true
        },
        "color_2": {
          "required": true
        },
        "amphitryon": {
          "required": true
        }
      ]
    }