properties:
  message: string
  data:
    type: object
    description: |
      Image of amphitryon of stand.
example:
  message: "Se obtuvo la información del anfitrión correctamente."
  data: {
    "image": "https://dev.cds.expo.aptitus.g3c.pe/anfitriona1.png"
  }
