properties:
  message: string
  name:
    type: string
    description: Name of file saved in S3.
  link: string
example:
  message: "Archivo subido correctamente."
  name: "fair-fdcb6432310998d42e929cd24f542a27.jpg"
  link: "https://dev.cde.expo.aptitus.g3c.pe/totem/fair-fdcb6432310998d42e929cd24f542a27.jpg"