post:
  description: |
    Create a new <<resourcePathName|!uppercamelcase|!singularize>>
  is: [ hasRequestItem: { typeName: <<typeName>>Request }, hasResponseItem: { typeName: <<typeName>>Response } ]